### ISSUE TITLE
When you query for a single post via URI, then the language is ignored

### ISSUE THREAD

**Issue by MobyDigg** [valu-digital/wp-graphql-polylang#46] opened 2021-05-06 10:44 UTC
When you query for a single post via URI, then the language parameter in the URL is ignored.
Query returns only the post in the standard language:

```
query MyQuery {
  teamMember(id: "/fr/team_members/lorem-ipsum/", idType: URI) {
    slug
    language {
      code
    }
    uri
  }
}
```

It should return the the French version for the query above.

**Comment by tim9009** [comment] 2021-05-10 15:31
I have the same issue now and it's blocking my entire project. Did you find a solution yet @MobyDigg?

**Comment by pangeaos** [comment] 2021-08-10 22:32
hi @gorkalaucirica, any help how to implement this filter? or how it works. thanks.

**Comment by esamattis** [comment] 2021-11-11 08:29
This is actually a duplicate of #35

Might want to read this https://github.com/valu-digital/wp-graphql-polylang/issues/35#issuecomment-779109950

Thank you for the filter workaround @gorkalaucirica

**Closed by esamattis** 2021-11-11 08:29 UTC
Labels: duplicate

**Comment by simplenotezy** [comment] 2022-01-13 22:26
Unfortunately I didn't have much luck with @gorkalaucirica's filter. Instead, this fixed it for my use-case:

```php
/**
 * Bugfix: prevent fetching pages from other languages. Without below filter, /de/about-us would resolve
 * to the english post called /en/about-us, which will give SEO issues. It also fixes an issue if two
 * posts in two different languages had the same post_name, the wrong one would/could be resolved
 * depending on what language you was requesting
 */

add_filter( 'request', function ( $query_args) {
    if(isset($query_args['graphql']) && isset($query_args['uri']) && $query_args['uri'] && isset($query_args['lang'])) {
        $explodedUri = explode('/', $query_args['uri']);
        if($explodedUri[0] !== $query_args['lang']) {
            // query was made without language slug in URI
            return $query_args;
        }

        unset($explodedUri[0]); // remove language slug from URL
        $uriWithoutLang = implode('/', $explodedUri); // rebuild the URI without the slug in front

        // search for the URI (post_name) without the language slug
        // as well as including the requested $lang in the query
        $query = new \WP_Query([
            'post_type'      => isset($query_args['post_type']) ? $query_args['post_type'] : 'any',
            'lang'           => $query_args['lang'],
            'posts_per_page' => 1,
            'post_status'    => 'publish',
            'name'           => $uriWithoutLang
        ]);

        if($query->have_posts() && isset($query->posts[0])) {
            // if we found a post, that's most likely the post we're looking for,
            // in the given language
            $query_args['p'] = $query->posts[0]->ID;
        } else {
            // we weren't able to find a post/page with the given URI and language
            // reset the query_args to return an empty response (to generate 404 page)
            // alternatively remove below line, if you wish to fallback to default behaviour
            // which may cause SEO issues, depending on your setup
            $query_args = [];
        }
    }
    return $query_args;
}, 	10, 2);
```

It's not the prettiest, but it does it's job. We had an issue if two pages was called the same, e.g. /de/about us and /en/about-us, when requesting the /de/about-us, it would resolve the english version.

Also we had an issue where if you requested an english slug, on the german prefix, if a german page did not exist with that name, it would return the english page - on the german site. Above filter also fixes that.
