### ISSUE TITLE
Does nodeByUri + graphql-polylang support getting the frontpage in several languages? 

### ISSUE THREAD

**Issue by krishaamer** [valu-digital/wp-graphql-polylang#71] opened 2022-03-01 01:30 UTC
@esamattis terve from Estonia! 

I was wondering if nodeByUri + graphql-polylang  should be able to retrieve the frontpage for each language if only given a language slug such as /fi or /de ?

I'm currently using PolyLang and PolyLang GraphQL but I'm only able to retrieve the default language and the frontpages in other languages result in null.)

I first asked the wp-graphql team (https://github.com/wp-graphql/wp-graphql/issues/2249) but they are no sure either so probably it's more appropriate to ask here.

Thanks
Kris

**Comment by evrenbal** [comment] 2022-03-06 23:05
I have encountered the same problem and looking for a fix.

I appreciate if anyone leads us to a solution.

Thanks in advance

**Comment by esamattis** [comment] 2022-03-11 12:40
Tere!

I think this is duplicate of https://github.com/valu-digital/wp-graphql-polylang/issues/35

Once that it solved you should be able to the other front pages as the translations of the frontpage you are asking for

```graphql
{
  page(id: "/fi", idType:URI) {
    title
    translations  {
      title
    }
  }
}
```

You could do just `id: "/"` which works now as well.

**Closed by esamattis** 2022-03-11 12:40 UTC
