### ISSUE TITLE
where filter doesn't work on page {}

### ISSUE THREAD

**Issue by pangeaos** [valu-digital/wp-graphql-polylang#57] opened 2021-08-05 20:13 UTC
I'm trying to get a page by URI and language but it's ignoring the /es/ and I only get the english content.

Instead of getting the Spanish content using translation { ... } node, Is there any way to filter the page and get only spanish?

Like this: `page(id: "/es/page", idType: URI, where: {language: ES}) { ... }`

![Screen Shot 2021-08-05 at 14 11 07](https://user-images.githubusercontent.com/221474/128414648-5addd562-5b0a-42c0-8c2d-ba558e1ce3d5.png)

**Comment by esamattis** [comment] 2021-11-11 08:17
Duplicate of https://github.com/valu-digital/wp-graphql-polylang/issues/46

There's also a filter based workaround you could try: https://github.com/valu-digital/wp-graphql-polylang/issues/46#issuecomment-852849101

**Closed by esamattis** 2021-11-11 08:17 UTC
